/** @type {import("tailwindcss").Config} */
const config = {
  theme: {
    extend: {
      spacing: {
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      fontFamily: {
        heading: ['var(--font-heading)'],
        body: ['var(--font-body)'],
        hylights: ['var(--font-hylights)'],
      },
      fontSize: {
        xs: ['var(--font-size-xs)', { lineHeight: 'var(--line-height-body)' }],
        sm: ['var(--font-size-sm)', { lineHeight: 'var(--line-height-body)' }],
        body: ['var(--font-size-body)', { lineHeight: 'var(--line-height-body)' }],
        h6: ['var(--font-size-h6)', { lineHeight: 'var(--line-height-heading)' }],
        h5: ['var(--font-size-h5)', { lineHeight: 'var(--line-height-heading)' }],
        h4: ['var(--font-size-h4)', { lineHeight: 'var(--line-height-heading)' }],
        h3: ['var(--font-size-h3)', { lineHeight: 'var(--line-height-heading)' }],
        h2: ['var(--font-size-h2)', { lineHeight: 'var(--line-height-heading)' }],
        h1: ['var(--font-size-h1)', { lineHeight: 'var(--line-height-heading)' }],
      },
      colors: {
        black: 'var(--color-black)',
        white: 'var(--color-white)',
        neutral: {
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
        },
        primary: {
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          DEFAULT: 'var(--color-primary-500)',
        },
        secondary: {
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          DEFAULT: 'var(--color-secondary-500)',
        },
        accent: {
          100: 'var(--color-accent-100)',
          200: 'var(--color-accent-200)',
          300: 'var(--color-accent-300)',
          400: 'var(--color-accent-400)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
          900: 'var(--color-accent-900)',
          DEFAULT: 'var(--color-accent-500)',
        },
        // comodi short-hand per background/testi
        background: 'var(--color-neutral-900)',
        surface: 'var(--color-neutral-800)',
        foreground: 'var(--color-neutral-100)',
        muted: 'var(--color-neutral-500)',
      },
    },
  },
  plugins: [],
};

export default config;
